### ISSUE TITLE
v2.2.0 auth redirect does not work with safari on iphone

### ISSUE THREAD

**Issue by ttomasz** [osmlab/osm-auth#121]
I tested v2.0.1, v2.1.0, and v2.2.0 with the demo page running in github codespace.

On older versions you can click "Login" button and you are redirected to osm page for auth. On newest version clicking "Login" buttons does not do anything.

Single page version on newest version works as expected.

**Comment by tyrasd** [comment]
I can confirm this issue. Unfortunately Safari (not only on iPhone) seems to have a bug which blocks the authentication popup from being opened in this case. The trigger is the usage of the WebCryptoAPI (introduced in #114). See #122 for a proposed workaround of this bug.

**Comment by bhousel** [comment]
Thanks.. Is the Safari bug tracked on https://bugs.webkit.org/ ?

**Comment by tyrasd** [comment]
I haven't found anything, so I opened https://bugs.webkit.org/show_bug.cgi?id=262775 now.

Note that I've also found a slightly better workaround for the problem (and updated #122 accordingly): Opening the popup window early in the chain (i.e. before any async code is invoked) seems to work in Safari and does not require browser sniffing (which was not so elegant to be honest).
