### ISSUE TITLE
Errors when using with NextJS App Directory: `DYNAMIC_SERVER_USAGE`; "no exported member"

### ISSUE THREAD

**Issue by tordans** [osmlab/osm-auth#124]
We are migrating radverkehrsatlas.de https://github.com/FixMyBerlin/atlas-app to NextJS using the App Directory and [BlitzJS](https://blitzjs.com/).

I notices to issues related to `osm-auth`. I want to document them here FYI and so others might find them. We will be moving our OsmAuth server side, so the issue is not pressing for us ATM.

## Error `Uncaught Error: DYNAMIC_SERVER_USAGE` when 

I documented the error at https://github.com/blitz-js/blitz/issues/4232 with a log of the error message. I now notice, that this error goes away once we remove the osm-auth dependency. So I assume this is where it came from.

Maybe relevant: In our previous setup as a regular React App, there was also a console error in dev mode related to some re-rendering. This might be the same issues that shows different in the different environments.

## Error `Module '"osm-auth"' has no exported member 'osmAuth'.ts(2305)`

I get this error on this line: `import { osmAuth } from 'osm-auth'` 

_Screenshot:_
<img width="557" alt="image" src="https://github.com/osmlab/osm-auth/assets/111561/47f95e77-8d42-4a82-9113-ec518cffde41">

**Comment by bhousel** [comment]
oh that is weird!
The named import is how we work with `osm-auth` in Rapid also:
https://github.com/facebook/Rapid/blob/acf8744a46a2fede677f1b7f4238996a811a7df3/modules/services/OsmService.js#L4

The error is coming from TypeScript so maybe there is a problem with how the export appears in our [osm-auth.d.ts file](https://github.com/osmlab/osm-auth/blob/main/src/osm-auth.d.ts).  I'm not really familiar with how this should look..
