### ISSUE TITLE
singlepage example

### ISSUE THREAD

**Issue by bmcbride** [osmlab/osm-auth#14]
Is there a full example that utilizes the `singlepage` option? I can't seem to get the `index.html` example working in conjunction with `land_single.html`, but I'm sure I'm probably missing something obvious...

**Comment by Monduiz** [comment]
Were you able to do it?

**Comment by iOiurson** [comment]
+1 on this one.

I can't get to get the `singlepage` option work :/
Everything is ok until the original page is reloaded, and at that point, I'm still not authenticated, which ends up in an infinite loop for authentication :/

**Comment by bhousel** [comment]
stale, but will try to make sure we have a decent example of single page use
