### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Monduiz** [osmlab/osm-auth#21]
I have setup the authentication but when iD reloads, the user is not authenticated and the user name (userLink) doesnt show in the info bar.

I am using this to authenticate:

 var auth = osmAuth({
            singlepage: true,
            oauth_consumer_key: '5A043yRSEugj4DJ5TljuapfnrflWDte8jTOcWLlT',
            oauth_secret: 'aB3jKq1TRsCOUrfOIZ6oQMEDmv2ptV76PA54NGLL',
            landing:"land_single.html"
        });
  document.getElementById('authenticate').onclick = function() {
            auth.authenticate(function() {
            });
        };

**Comment by Monduiz** [comment]
adding landing: "index.html" works but iD doesnt show the user name in the info bar. Its as if the user is not authenticated. I must be missing something.

**Comment by Monduiz** [comment]
When using land_single.html, after granting access, you are returned to the app url with
`
            var oauth_token = stringQs(window.location.href.split('?')[1]).oauth_token;
            location.href = '/?oauth_token=' + oauth_token;`

However, even if location.href loads the app with "?oauth_token=" iD doesnt load with the user's authentication.

**Comment by bhousel** [comment]
I believe it's up to the landing page to get a `oauth_token_secret` using the `oauth_token`.  I think the `land_single.html` page in this repository in incomplete, so I'll try to take a look and see what it's missing.

**Comment by Monduiz** [comment]
Ok thanks, and if you know of a way to load the authentication page in another language, that would solve all of the remaining issues I have.

**Comment by Monduiz** [comment]
I tried a few things in land_single but I am not getting anywhere. I fail to understand what its supposed to do with stringsQ and it looks like all it does is paste a string in the url which iD doesnt read to proceed to an authenticated session.

**Comment by Monduiz** [comment]
So far, what I get is an authentication on the OSM login page and callback to iD app with an oauth_token url parameter but not logged in with iD.

**Comment by bhousel** [comment]
stale, but will try to make sure we have a decent example of single page use
