### ISSUE TITLE
callback assumes the name of the page is index.html

### ISSUE THREAD

**Issue by HarelM** [osmlab/osm-auth#22]
The following code assumes the page name is index.html
```js
oauth_callback: location.href.replace('index.html', '')
                    .replace(/#.*/, '').replace(location.search, '') + o.landing
```
I was trying it on a page called auth.html (currently for testing) and it failed.
I think a another option should be added, something like ```indexPage``` or ```pageName``` or whatever you think is appropriate that defaults to ```index.html```

**Comment by Monduiz** [comment]
Does it still fail if you add landing: 'auth.html' in your osmAauth options?

**Comment by HarelM** [comment]
Yes. Even tried full address.

**Comment by Monduiz** [comment]
Ok, I have the same issue. I am developing a bilingual version and it doesnt work on my other language page (its not index.html). The way around this is to create a separare modified version of osmauth.js that you load into the non-index.html with the name of teh page you are using. Hackish and I would prefer the solution you are suggesting.

**Comment by tmcw** [comment]
Fixed in https://github.com/osmlab/osm-auth/pull/25

**Comment by bhousel** [comment]
not sure this is the right solution, see https://github.com/osmlab/osm-auth/pull/25#issuecomment-258462946

**Comment by HarelM** [comment]
Feel free to fix it any other way you think is correct. I tried to change as less as possible in order not to change the current behavior (keep it backwards compatible).

**Comment by Monduiz** [comment]
When I try the new osmauth.js file, authentication is unresponsive. When I click in my menu, nothing happens. When I go back to the previous version, it loads.

**Comment by Monduiz** [comment]
I did more testing and I get this error in Safari: In Safari I get an error: Failed to load resource: the server responded with a status of 401 (Unauthorized) http://www.openstreetmap.org/api/0.6/user/details

**Comment by Monduiz** [comment]
This is weird. I normally use http-server to test locally and its not working in Safari and Firefox. However, when I run Node development server with npm start, it works in all browsers.

**Comment by Monduiz** [comment]
I see that the same problem exists in iD. If a different page is used instead of index, like indexFr, the same problem happens with the built-in authorization with the flow: edit->save->authenticate.
