### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by HarelM** [osmlab/osm-auth#30]
OAuth 1.x has security issues, especially with this javascript client because you need to specify the consumer secret.
Are there any plans to migrate to OAuth2?

**Comment by tmcw** [comment]
This is a client for the OpenStreetMap API, and I don't see any evidence that it supports OAuth 2. So, no, this doesn't use OAuth 2.

**Comment by HarelM** [comment]
I'm sorry, I thought this repository had some accountability to the development made by the osm team. Do you know who I can contact in order to push forward the OAuth2 protocol.

**Comment by tmcw** [comment]
The [openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) repo tracks the website, including the bit that does OAuth. fwiw, it may support OAuth 2, but I can't find any documentation for it.

**Comment by HarelM** [comment]
Thanks for your help, I submitted an issue there, I hope they will end up implementing it...
