### ISSUE TITLE
Do you plan to support for TypeScript declaration?

### ISSUE THREAD

**Issue by tom-konda** [osmlab/osm-auth#37]
Hi,

I was created a TypeScript declaration file for osm-auth lib before.
If you will have a plan for supporting TypeScript declaration,
I would contribute this file to the project.

**Comment by bhousel** [comment]
Thanks @tom-konda, I haven't used TypeScript before, but I recognize its usefulness and would happily accept a PR that adds it.

**Comment by tmcw** [comment]
Merged in #39
