### ISSUE TITLE
Moving source files

### ISSUE THREAD

**Issue by nyurik** [osmlab/osm-auth#55]
Hi, would it be possible to move all source code files into a subdir, e.g. `src/`?  The root dir seems a bit crowded, had to look closely to figure out what is the code and what are just the docs.  Also, still a bit confused about the auto-generated files. Should they be checked in at all?

Thanks for the great example!

**Comment by bhousel** [comment]
Tagging @kepta - I think he might be planning a rewrite of this library.

I think it makes sense to move `osmauth.js` and `osmauth.min.js` into a `dist/` folder.. I have no idea where the `.ts` file came from.  It doesn't matter to me whether they are checked in or not.

The real source code for the library is just `index.js`.
