### ISSUE TITLE
401 and header

### ISSUE THREAD

**Issue by zetx16** [osmlab/osm-auth#60]
When creating the changes, I get the error 401 (Unauthorized). I solved the problem by adding the `options: { header: { 'Content-Type': 'text/xml' } }` shots as in iD. Perhaps you should write about this in the 'readme'.

**Comment by bhousel** [comment]
I think that setting the Content Type header has more to do with working with OSM API than anything internal to this library.  Not every API call requires that option.

Going to close here, but I'd definitely be ok if somebody sent a PR with a FAQ on how to use this library.
