### ISSUE TITLE
Allow requests without authorization

### ISSUE THREAD

**Issue by PanierAvide** [osmlab/osm-auth#62]
Hello,
With some developers, we started working on a JS library to allow easy requesting of OSM API (meaning with promises, returning clean JS objects...), and we will use osm-auth in order to handle authenticated calls.
As our lib will also be able to perform API calls which don't need authentication (like getting notes in an area), we are wondering if calls without authentication could be enabled in osm-auth ? For the while, `xhr` method rejects you if you're not authenticated. This implies that any other lib should maintain its own `xhr` method for not authenticated calls, which is not optimal as we could reuse the one in osm-auth.
Does this makes sense to you ? We are ready to propose a pull-request to enable this.
Regards.

**Comment by bhousel** [comment]
> For the while, xhr method rejects you if you're not authenticated. This implies that any other lib should maintain its own xhr method for not authenticated calls, which is not optimal as we could reuse the one in osm-auth.
> Does this makes sense to you ?

Yes, I think this is best.. I kind of feel like knowing which calls in the OSM API should be auth'd / not auth'd is a complicated detail.  Even in iD we have logic for trying _certain_ calls without auth and then upgrading them to auth if the user is rate limited - and logic for trying _certain other_ calls with auth, and then retrying them without auth if there is an auth issue (e.g. oauth tokens revoked).

I'd also add that it is possible that the rules for which OSM API calls require auth will change very soon with the adoption of the GDPR rules.  So it's probably better to just wait a few months and see what effect the new rules have.  We might find that more API calls require auth after May.

**Comment by PanierAvide** [comment]
In fact, I was more meaning like adding a parameter when calling `xhr` in order to force a not authenticated call. This choice would be in the hand of library users' instead of being an unbreakable default.
Thanks for giving the iD example, I see in source code that currently unauthenticated calls are built upon d3. So you think unauthenticated calls should be managed outside osm-auth for now, and not as an user-defined parameter of osm-auth ?

**Comment by bhousel** [comment]
> So you think unauthenticated calls should be managed outside osm-auth for now, and not as an user-defined parameter of osm-auth ?

Yes for now - we might change that later.

But yeah I do see as implementation detail - 
1. knowing which calls can use auth vs unauth
2. upgrading the user to auth, downgrading the user to unauth, handling failures

You gave the example of an app that needs to search osm notes.  This app would only need auth for certain things, but it knows which things need it and which don't.  And those certain things may change after May.  

It's just easier for me to just say "this stuff is out of scope for osm-auth, and we only will handle the part of taking a call and adding oauth headers to it".  Also this library is kind of getting old and is probably due for a rewrite, so I don't want to sink too much effort into it.

**Comment by PanierAvide** [comment]
That's clear, thanks for your fast and detailed answer :-)
