### ISSUE TITLE
How to pass another URL to use OAuth to another project ?

### ISSUE THREAD

**Issue by pyrog** [osmlab/osm-auth#69]
I would use OAuth with OpenStreetMap and I would like to use it with Wikimedia Commons with one library (osm-auth).

According to [index.js#L236](https://github.com/osmlab/osm-auth/blob/master/index.js#L236), I guess that I should use the url parameters somewhere, and that's all ?

**Comment by bhousel** [comment]
It might work if you just make a second instance of `osmAuth` but change all the options so that it isn't pointing at OSM?   
It might work?
